name: Publish binaries on Release
on:
  release:
    types: [created]

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v6

      - name: Get dependencies
        run: |
          docker build -t myrepo:latest -f Dockerfile-release .
          id=$(docker create myrepo:latest)
          docker cp $id:/tmp/dnsmonster-linux-amd64.bin /tmp/dnsmonster-linux-amd64.bin
          docker cp $id:/tmp/dnsmonster-windows-amd64.exe /tmp/dnsmonster-windows-amd64.exe
          docker cp $id:/tmp/dnsmonster-latest.rpm /tmp/dnsmonster-latest.rpm
          docker cp $id:/tmp/dnsmonster-latest.deb /tmp/dnsmonster-latest.deb
          strip --strip-all /tmp/dnsmonster-linux-amd64.bin
          tar czf /tmp/dnsmonster-linux-amd64.bin.tar.gz -C /tmp/ dnsmonster-linux-amd64.bin

      - name: Upload Linux binary to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: /tmp/dnsmonster-linux-amd64.bin.tar.gz
          asset_name: dnsmonster-musl-static-stripped-amd64.tar.gz
          tag: ${{ github.ref }}
          overwrite: true
          body: ""

      - name: Upload windows binary for signing
        id: upload-windows-artifact
        uses: actions/upload-artifact@v4
        with:
          path: /tmp/dnsmonster-windows-amd64.exe
          name: dnsmonster-windows-amd64-unsigned

      - name: Sign Windows binary with SignPath
        id: sign-windows
        uses: signpath/github-action-submit-signing-request@v1
        with:
          api-token: "${{ secrets.SIGNPATH_API_TOKEN }}"
          organization-id: "${{ secrets.SIGNPATH_ORGANIZATION_ID }}"
          project-slug: "${{ secrets.SIGNPATH_PROJECT_SLUG }}"
          signing-policy-slug: "${{ secrets.SIGNPATH_SIGNING_POLICY_SLUG }}"
          github-artifact-id: "${{ steps.upload-windows-artifact.outputs.artifact-id }}"
          wait-for-completion: true
          output-artifact-directory: /tmp/signed

      - name: Upload signed windows binary to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: /tmp/signed/dnsmonster-windows-amd64.exe
          asset_name: dnsmonster-windows-amd64.exe
          tag: ${{ github.ref }}
          overwrite: true
          body: ""

      - name: Upload rpm to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: /tmp/dnsmonster-latest.rpm
          asset_name: dnsmonster-centos-rhel-ami-x86_64.rpm
          tag: ${{ github.ref }}
          overwrite: true
          body: ""

      - name: Upload deb to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: /tmp/dnsmonster-latest.deb
          asset_name: dnsmonster-debian-ubuntu-x86_64.deb
          tag: ${{ github.ref }}
          overwrite: true
          body: ""

    # - uses: actions/upload-artifact@v2
    #   with:
    #     name: dnsmonster-latest.deb
    #     path: /tmp/dnsmonster*.deb
